# Generated by Django 5.2.8 on 2025-11-10 12:08

import tcikets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcikets', '0002_alter_procedure_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=tcikets.models.procedure_attachment_path),
        ),
        migrations.AlterField(
            model_name='procedureimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=tcikets.models.procedure_image_path),
        ),
    ]
