# Generated by Django 5.2.8 on 2025-11-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcikets', '0003_alter_procedureattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedureattachment',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Pièce jointe de procédure'},
        ),
    ]
