# Generated by Django 5.2.8 on 2025-11-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcikets', '0004_alter_procedureattachment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureimage',
            name='file_extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
