# Generated by Django 5.2.8 on 2025-11-10 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcikets', '0005_procedureimage_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketimage',
            name='file_extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ticketimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
