# Generated by Django 5.2.8 on 2025-11-10 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcikets', '0006_ticketimage_file_extension_ticketimage_file_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='procedureversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='procedureversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='procedureversion',
            name='procedure',
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='procedureattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='procedureimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proceduretag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='procedure',
            name='tcikets_pro_status_202d69_idx',
        ),
        migrations.RemoveIndex(
            model_name='procedure',
            name='tcikets_pro_categor_0beb29_idx',
        ),
        migrations.RemoveIndex(
            model_name='procedure',
            name='tcikets_pro_views_2b9699_idx',
        ),
        migrations.RemoveIndex(
            model_name='procedure',
            name='tcikets_pro_feature_56153b_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='procedure',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Téléphone au format +242055506688 (8-15 chiffres).', regex='^\\+?242?\\d{8,15}$')]),
        ),
        migrations.DeleteModel(
            name='ProcedureVersion',
        ),
    ]
