# Generated by Django 5.2.8 on 2025-11-11 08:29

import tcikets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcikets', '0007_alter_procedureversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interventionimage',
            name='file_extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='interventionimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interventionimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventionimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=tcikets.models.intervention_image_path),
        ),
    ]
