# Generated by Django 5.2.8 on 2025-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcikets', '0008_interventionimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['-intervention_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['ticket', '-intervention_date'], name='tcikets_int_ticket__33d8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['technician', 'status'], name='tcikets_int_technic_0a3802_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['status', '-intervention_date'], name='tcikets_int_status_66ddb2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['ticket', 'timestamp'], name='tcikets_mes_ticket__d6e091_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', '-timestamp'], name='tcikets_mes_user_id_80ebef_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['status', '-created_at'], name='tcikets_pro_status_0b10ed_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['category', 'status'], name='tcikets_pro_categor_a6d2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['author', 'status'], name='tcikets_pro_author__641bef_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['-views'], name='tcikets_pro_views_2b9699_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['featured', 'status'], name='tcikets_pro_feature_92fb95_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='tcikets_tic_status_35ebd0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['client', 'status'], name='tcikets_tic_client__bb1d94_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['technician', 'status'], name='tcikets_tic_technic_180a90_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-created_at'], name='tcikets_tic_created_350689_idx'),
        ),
    ]
